version: '2'
services:
    odoo_base:
        image: $ODOO_IMAGE:$ODOO_VERSION
        external_links:
            - aeroo-docs:aeroo
        # podria ir aca pero puede ser mas practico en quien extiende
        ports:
            - "9089:8069"
            - "6072:8072"
        volumes:
            - ./data/custom-addons:/opt/odoo/custom-addons
            - odoo_data:/var/lib/odoo/
        env_file:
            - .env
